# Configuración para la App 1
[build]
  base = "app1"
  command = "npm run build"
  publish = "/dist/app1"

# Configuración para la App 2
[[redirects]]
  from = "/app2/*"
  to = "/dist/app2/:splat"
  status = 200

# Configuración para el Shell
[[redirects]]
  from = "/shell/*"
  to = "/dist/shell/:splat"
  status = 200
